<?xml version="1.0"?>
<package format="3">
  <name>infield_robotics_workshop</name>
  <version>0.0.1</version>
  <description>Exercises for the Infield Robotics Workshop.</description>
  <maintainer email="tschuette@atb-potsdam.de">Tjark Schuette</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>tf2_ros_py</exec_depend>
  <exec_depend>tf_transformations</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
